package dev.cya.app.identity

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The key the shared database is encrypted with (ADR-010).
 *
 * A 32-byte random value, generated once and never leaving the device. It is not *stored* in the
 * clear: it is sealed with an AES-GCM key that lives inside the Android Keystore — hardware-backed
 * where the device has a TEE or StrongBox — and only the sealed blob goes into SharedPreferences.
 * Getting the database file off a device therefore gets you ciphertext, and getting the preferences
 * too gets you a blob that only that device's Keystore can open.
 *
 * **It is a raw key, deliberately.** SQLCipher's usual `PRAGMA key = 'passphrase'` runs 256,000
 * PBKDF2 iterations on *every open* — several hundred milliseconds on mid-range hardware. The
 * Share Sheet capture path opens this database cold, from an activity with no Flutter engine, and
 * is measured in tens of milliseconds (PRD §9.2, §5.4). Paying a KDF there would be a 3–4×
 * regression on the product's reason to exist, to stretch a value that is already 256 bits of
 * entropy and therefore has nothing to stretch. `PRAGMA key = "x'<64 hex>'"` skips derivation
 * entirely; the Keystore does the protecting.
 */
internal object DatabaseKey {

    private const val PREFS = "cya_secure"
    private const val PREF_WRAPPED = "db_key_wrapped"
    private const val KEYSTORE_ALIAS = "cya_db_wrapping_key"
    private const val KEYSTORE = "AndroidKeyStore"
    private const val TRANSFORMATION = "AES/GCM/NoPadding"

    private const val KEY_BYTES = 32
    private const val GCM_IV_BYTES = 12
    private const val GCM_TAG_BITS = 128

    @Volatile
    private var cached: String? = null

    /**
     * The key as 64 lowercase hex characters, ready for `PRAGMA key = "x'…'"`.
     *
     * Cached in memory: every native surface (capture, notification action, widget, boot) opens the
     * database, and unwrapping through the Keystore on each one would put a JCE round trip back on
     * the path this design exists to keep short.
     */
    @Synchronized
    fun hex(context: Context): String {
        cached?.let { return it }
        val prefs = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        val stored = prefs.getString(PREF_WRAPPED, null)

        val raw = if (stored == null) {
            ByteArray(KEY_BYTES).also { fresh ->
                java.security.SecureRandom().nextBytes(fresh)
                prefs.edit().putString(PREF_WRAPPED, seal(fresh)).commit()
            }
        } else {
            unseal(stored)
        }
        return raw.toHex().also { cached = it }
    }

    /**
     * The key in SQLCipher's raw-key literal form, `x'<64 hex>'`.
     *
     * The same string works as the password handed to `sqlite3_key` by the Android binding and as
     * the right-hand side of Dart's `PRAGMA key`, because SQLCipher inspects the key material for
     * exactly this shape and uses the bytes verbatim rather than deriving from them.
     */
    fun rawKey(context: Context): String = "x'${hex(context)}'"

    // --- Keystore sealing -------------------------------------------------

    private fun seal(raw: ByteArray): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, wrappingKey())
        val sealed = cipher.doFinal(raw)
        // iv || ciphertext. The IV is generated by the provider and is not secret; it only has to
        // be unique, and it is written exactly once per install.
        val blob = cipher.iv + sealed
        return Base64.encodeToString(blob, Base64.NO_WRAP)
    }

    private fun unseal(stored: String): ByteArray {
        val blob = Base64.decode(stored, Base64.NO_WRAP)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(
            Cipher.DECRYPT_MODE,
            wrappingKey(),
            GCMParameterSpec(GCM_TAG_BITS, blob, 0, GCM_IV_BYTES),
        )
        return cipher.doFinal(blob, GCM_IV_BYTES, blob.size - GCM_IV_BYTES)
    }

    private fun wrappingKey(): SecretKey {
        val keystore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        (keystore.getEntry(KEYSTORE_ALIAS, null) as? KeyStore.SecretKeyEntry)
            ?.let { return it.secretKey }

        val generator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            KEYSTORE,
        )
        generator.init(
            KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                // Explicitly NOT `setUserAuthenticationRequired(true)`. A reminder has to be able
                // to fire, and be resolved from the shade, on a locked phone (PRD §3.4) — tying
                // the database to the lock screen would make the alarm path fail exactly when the
                // product is supposed to work. The app's own PIN (ADR-010) is what gates *reading*
                // promises; this key gates reading the *file*.
                .build(),
        )
        return generator.generateKey()
    }

    private fun ByteArray.toHex(): String {
        val out = StringBuilder(size * 2)
        for (byte in this) out.append("%02x".format(byte))
        return out.toString()
    }
}
